# Setup
title:            'State of Connecticut'
tagline:          'P20 WIN Data Governance Manual'
description:      'Data governance documentation for P20 WIN'

author:
  name:           'State of Connecticut'
  url:            https://github.com/CTOpenData/p20win-data-governance-manual

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/CTOpenData/p20win-data-governance-manual
